"""Seed dataset for Ghost Space: rooms, one realistic day of bookings, history.

Rooms are bound to **existing campus graph nodes** so reachability can be
answered by the real router. Three of them sit behind the broken Health Sciences
lift or the blocked More Hall ramp, which is what makes the flagship demo beat
work: a step-free student asks for a room and gets told exactly why the closest
one is excluded.

The booking day is deterministic (fixed offsets from the demo anchor) and about
30% of bookings are ghosts, matching the real-world figure that drives the whole
product pitch.
"""

from __future__ import annotations

from typing import Any

#: 14 rooms across 4 campus buildings, each linked to a seeded graph node.
ROOMS: list[dict[str, Any]] = [
    # --- Suzzallo / Allen (Central) -------------------------------------
    {
        "id": "rm_suzz_101",
        "name": "Suzzallo 101 Lecture Hall",
        "building": "Suzzallo Library",
        "floor": "1",
        "capacity": 120,
        "node_id": "bld_suzzallo",
        "is_step_free_access": True,
        "has_accessible_features": True,
        "power_kw": 4.2,
        "accessible_notes": "Level 1, step-free from the south ramp entrance. Hearing loop, 6 wheelchair spaces.",
    },
    {
        "id": "rm_suzz_214",
        "name": "Suzzallo 214 Seminar Room",
        "building": "Suzzallo Library",
        "floor": "2",
        "capacity": 24,
        "node_id": "bld_suzzallo",
        "is_step_free_access": True,
        "has_accessible_features": True,
        "power_kw": 1.1,
        "accessible_notes": "Lift access from the south ramp entrance. Adjustable-height bench at the front desk.",
    },
    {
        "id": "rm_allen_402",
        "name": "Allen 402 Research Commons",
        "building": "Allen Library",
        "floor": "4",
        "capacity": 40,
        "node_id": "bld_allen_lib",
        "is_step_free_access": True,
        "has_accessible_features": True,
        "power_kw": 1.8,
        "accessible_notes": "Lift to level 4. Wide aisles throughout.",
    },
    {
        "id": "rm_allen_120",
        "name": "Allen 120 Study Room",
        "building": "Allen Library",
        "floor": "1",
        "capacity": 8,
        "node_id": "bld_allen_lib",
        "is_step_free_access": True,
        "has_accessible_features": False,
        "power_kw": 0.6,
        "accessible_notes": "Ground floor, step-free. No hearing loop.",
    },
    {
        "id": "rm_suzz_305",
        "name": "Suzzallo 305 Reading Room",
        "building": "Suzzallo Library",
        "floor": "3",
        "capacity": 16,
        "node_id": "bld_suzzallo",
        "is_step_free_access": True,
        "has_accessible_features": False,
        "power_kw": 1.3,
    },
    # --- HUB / Odegaard (student services) -------------------------------
    {
        "id": "rm_hub_210",
        "name": "HUB 210 Meeting Room",
        "building": "Husky Union Building",
        "floor": "2",
        "capacity": 14,
        "node_id": "bld_hub",
        "is_step_free_access": True,
        "has_accessible_features": True,
        "power_kw": 0.9,
        "accessible_notes": "Lift from the main step-free entrance. Adjustable table available on request.",
    },
    {
        "id": "rm_hub_006",
        "name": "HUB 006 Lounge",
        "building": "Husky Union Building",
        "floor": "G",
        "capacity": 30,
        "node_id": "bld_hub",
        "is_step_free_access": True,
        "has_accessible_features": False,
        "power_kw": 1.4,
    },
    {
        "id": "rm_odeg_250",
        "name": "Odegaard 250 Group Room",
        "building": "Odegaard Library",
        "floor": "2",
        "capacity": 18,
        "node_id": "bld_odegaard",
        "is_step_free_access": True,
        "has_accessible_features": True,
        "power_kw": 1.1,
    },
    {
        "id": "rm_odeg_118",
        "name": "Odegaard 118 Quiet Room",
        "building": "Odegaard Library",
        "floor": "1",
        "capacity": 10,
        "node_id": "bld_odegaard",
        "is_step_free_access": True,
        "has_accessible_features": False,
        "power_kw": 0.7,
    },
    # --- More Hall (Engineering) -----------------------------------------
    {
        "id": "rm_more_122",
        "name": "More Hall 122 Seminar Room",
        "building": "More Hall",
        "floor": "1",
        "capacity": 28,
        "node_id": "bld_more",
        "is_step_free_access": True,
        "has_accessible_features": True,
        "power_kw": 1.5,
        "accessible_notes": (
            "Step-free ONLY via the east ramp. When a barrier is reported on that "
            "ramp this room becomes unreachable for wheelchair users."
        ),
    },
    {
        "id": "rm_more_212",
        "name": "More Hall 212 Project Room",
        "building": "More Hall",
        "floor": "2",
        "capacity": 12,
        "node_id": "bld_more",
        "is_step_free_access": True,
        "has_accessible_features": True,
        "power_kw": 1.0,
        "accessible_notes": "Lift access from the level 1 lobby. Ramp-dependent in practice.",
    },
    {
        "id": "rm_more_318",
        "name": "More Hall 318 Teaching Lab",
        "building": "More Hall",
        "floor": "3",
        "capacity": 32,
        "node_id": "more_3f",
        "is_step_free_access": True,
        "has_accessible_features": True,
        "power_kw": 2.2,
        "accessible_notes": "Level 3, lift only. Two height-adjustable lab benches.",
    },
    {
        "id": "rm_more_404",
        "name": "More Hall 404 Seminar (stairs only)",
        "building": "More Hall",
        "floor": "4",
        "capacity": 22,
        "node_id": "more_3f",
        "is_step_free_access": False,
        "has_accessible_features": False,
        "power_kw": 1.2,
        "accessible_notes": "Reached by the grand stair flight. No lift on this level.",
    },
    # --- Health Sciences (Medical) ---------------------------------------
    {
        "id": "rm_hsb_302",
        "name": "Health Sciences 302 Clinical Teaching Room",
        "building": "Health Sciences Building",
        "floor": "3",
        "capacity": 20,
        "node_id": "hsb_clinic_3",
        "is_step_free_access": True,
        "has_accessible_features": True,
        "power_kw": 1.9,
        "accessible_notes": (
            "Level 3 is lift-only. When Lift Bank A is reported broken this room "
            "is unreachable step-free and Ghost Space excludes it with a reason."
        ),
    },
    {
        "id": "rm_hsb_118",
        "name": "Health Sciences 118 Health Lab",
        "building": "Health Sciences Building",
        "floor": "1",
        "capacity": 26,
        "node_id": "bld_health_sci",
        "is_step_free_access": True,
        "has_accessible_features": True,
        "power_kw": 1.7,
        "accessible_notes": "Ground floor via the south ramp entrance.",
    },
    {
        "id": "rm_hsb_215",
        "name": "Health Sciences 215 Simulation Suite",
        "building": "Health Sciences Building",
        "floor": "2",
        "capacity": 16,
        "node_id": "bld_health_sci",
        "is_step_free_access": True,
        "has_accessible_features": True,
        "power_kw": 2.4,
    },
    # --- Odegaard-adjacent lecture rooms ---------------------------------
    {
        "id": "rm_suzz_aud",
        "name": "Suzzallo Auditorium",
        "building": "Suzzallo Library",
        "floor": "G",
        "capacity": 200,
        "node_id": "bld_suzzallo",
        "is_step_free_access": True,
        "has_accessible_features": True,
        "power_kw": 6.5,
        "accessible_notes": "Level G, step-free. Full hearing loop and dedicated wheelchair platform.",
    },
    {
        "id": "rm_hub_118",
        "name": "HUB 118 Quiet Study",
        "building": "Husky Union Building",
        "floor": "1",
        "capacity": 12,
        "node_id": "bld_hub",
        "is_step_free_access": True,
        "has_accessible_features": False,
        "power_kw": 0.8,
    },
    {
        "id": "rm_hub_312",
        "name": "HUB 312 Student Org Room",
        "building": "Husky Union Building",
        "floor": "3",
        "capacity": 25,
        "node_id": "bld_hub",
        "is_step_free_access": True,
        "has_accessible_features": True,
        "power_kw": 1.3,
    },
]


#: One realistic teaching day. Offsets are minutes from 08:00 on the demo date.
#: ``will_show=False`` marks a ghost: nobody will ever check in, so the engine
#: must decide to release it.
BOOKINGS: list[dict[str, Any]] = [
    # --- morning ---------------------------------------------------------
    {"room": "rm_suzz_101", "organizer": "faculty", "start": 8 * 60, "end": 9 * 60 + 30, "attendees": 95, "will_show": True, "title": "CHEM 142 lecture"},
    {"room": "rm_suzz_214", "organizer": "faculty", "start": 9 * 60, "end": 10 * 60 + 30, "attendees": 18, "will_show": True, "title": "HIST 203 seminar"},
    {"room": "rm_hub_210", "organizer": "club", "start": 9 * 60, "end": 10 * 60, "attendees": 10, "will_show": True, "title": "Robotics club sync"},
    {"room": "rm_allen_402", "organizer": "faculty", "start": 9 * 60, "end": 11 * 60, "attendees": 32, "will_show": True, "title": "Research group meeting"},
    {"room": "rm_odeg_250", "organizer": "faculty", "start": 10 * 60, "end": 11 * 60 + 30, "attendees": 14, "will_show": True, "title": "LING 310 group"},
    {"room": "rm_hub_006", "organizer": "admin", "start": 10 * 60, "end": 11 * 60, "attendees": 20, "will_show": False, "title": "Staff briefing"},
    {"room": "rm_suzz_305", "organizer": "faculty", "start": 10 * 60, "end": 12 * 60, "attendees": 12, "will_show": False, "title": "GRAD 511 (cancelled)"},
    {"room": "rm_more_122", "organizer": "faculty", "start": 10 * 60, "end": 11 * 60 + 30, "attendees": 22, "will_show": True, "title": "CS 225 lecture"},
    {"room": "rm_hsb_118", "organizer": "faculty", "start": 11 * 60, "end": 12 * 60 + 30, "attendees": 20, "will_show": True, "title": "BIO 150 lab"},
    {"room": "rm_allen_120", "organizer": "student_group", "start": 11 * 60, "end": 12 * 60, "attendees": 6, "will_show": True, "title": "Study group"},
    # --- midday ----------------------------------------------------------
    {"room": "rm_suzz_aud", "organizer": "admin", "start": 12 * 60, "end": 13 * 60 + 30, "attendees": 180, "will_show": True, "title": "Convocation rehearsal"},
    {"room": "rm_more_318", "organizer": "faculty", "start": 12 * 60, "end": 14 * 60, "attendees": 28, "will_show": True, "title": "EE 401 lab"},
    {"room": "rm_hub_312", "organizer": "club", "start": 12 * 60, "end": 13 * 60, "attendees": 18, "will_show": False, "title": "Student org board meeting"},
    {"room": "rm_odeg_118", "organizer": "student_group", "start": 12 * 60 + 30, "end": 13 * 60 + 30, "attendees": 8, "will_show": False, "title": "Book club"},
    {"room": "rm_hsb_302", "organizer": "faculty", "start": 13 * 60, "end": 14 * 60 + 30, "attendees": 16, "will_show": True, "title": "Clinical skills"},
    {"room": "rm_hub_118", "organizer": "student_group", "start": 13 * 60, "end": 14 * 60, "attendees": 9, "will_show": True, "title": "Peer tutoring"},
    {"room": "rm_suzz_214", "organizer": "club", "start": 14 * 60, "end": 15 * 60, "attendees": 15, "will_show": False, "title": "Debate team prep"},
    {"room": "rm_allen_402", "organizer": "faculty", "start": 14 * 60, "end": 16 * 60, "attendees": 30, "will_show": True, "title": "Thesis committee"},
    {"room": "rm_hsb_215", "organizer": "faculty", "start": 14 * 60, "end": 15 * 60 + 30, "attendees": 14, "will_show": False, "title": "SIM 480 (room change)"},
    {"room": "rm_more_212", "organizer": "student_group", "organizer_label": "", "start": 15 * 60, "end": 16 * 60, "attendees": 10, "will_show": True, "title": "Capstone team"},
    {"room": "rm_hub_006", "organizer": "club", "start": 15 * 60, "end": 16 * 60 + 30, "attendees": 22, "will_show": True, "title": "Film society screening"},
    {"room": "rm_suzz_305", "organizer": "faculty", "start": 15 * 60, "end": 17 * 60, "attendees": 11, "will_show": True, "title": "ARCH 420 studio"},
    {"room": "rm_more_404", "organizer": "faculty", "start": 16 * 60, "end": 17 * 60 + 30, "attendees": 18, "will_show": False, "title": "MATH 307 (stairs-only room)"},
    # --- afternoon -------------------------------------------------------
    {"room": "rm_odeg_250", "organizer": "student_group", "start": 16 * 60, "end": 17 * 60, "attendees": 12, "will_show": True, "title": "Society meeting"},
    {"room": "rm_hsb_118", "organizer": "faculty", "start": 16 * 60, "end": 17 * 60 + 30, "attendees": 22, "will_show": True, "title": "PH 220 lab"},
    {"room": "rm_allen_120", "organizer": "club", "start": 16 * 60 + 30, "end": 17 * 60 + 30, "attendees": 5, "will_show": False, "title": "Coding club standup"},
    {"room": "rm_hub_210", "organizer": "faculty", "start": 17 * 60, "end": 18 * 60, "attendees": 11, "will_show": False, "title": "POL 210 (room change)"},
    {"room": "rm_suzz_214", "organizer": "admin", "start": 17 * 60, "end": 18 * 60 + 30, "attendees": 16, "will_show": False, "title": "Committee session"},
    {"room": "rm_more_122", "organizer": "club", "start": 17 * 60, "end": 18 * 60 + 30, "attendees": 20, "will_show": True, "title": "Robotics build night"},
    {"room": "rm_hsb_302", "organizer": "faculty", "start": 18 * 60, "end": 19 * 60 + 30, "attendees": 15, "will_show": False, "title": "Evening clinic prep"},
    {"room": "rm_odeg_118", "organizer": "student_group", "start": 18 * 60, "end": 19 * 60, "attendees": 7, "will_show": False, "title": "Language exchange"},
    {"room": "rm_allen_402", "organizer": "club", "start": 18 * 60, "end": 19 * 60 + 30, "attendees": 24, "will_show": False, "title": "Entrepreneurship meetup"},
    {"room": "rm_hub_312", "organizer": "student_group", "start": 19 * 60, "end": 20 * 60 + 30, "attendees": 19, "will_show": False, "title": "Weekly general meeting"},
    {"room": "rm_suzz_101", "organizer": "faculty", "start": 19 * 60, "end": 20 * 60 + 30, "attendees": 80, "will_show": True, "title": "CHEM 142 evening section"},
    {"room": "rm_more_212", "organizer": "admin", "start": 19 * 60, "end": 21 * 60, "attendees": 8, "will_show": False, "title": "Department meeting"},
    {"room": "rm_hub_118", "organizer": "club", "start": 20 * 60, "end": 21 * 60 + 30, "attendees": 10, "will_show": True, "title": "Late study group"},
    {"room": "rm_suzz_305", "organizer": "student_group", "start": 20 * 60, "end": 21 * 60 + 30, "attendees": 9, "will_show": True, "title": "Grad student journal club"},
    {"room": "rm_hsb_215", "organizer": "club", "start": 20 * 60, "end": 22 * 60, "attendees": 13, "will_show": True, "title": "EMS practice"},
    {"room": "rm_odeg_250", "organizer": "faculty", "start": 20 * 60, "end": 21 * 60 + 30, "attendees": 15, "will_show": False, "title": "MUS 289 elective"},
    {"room": "rm_more_318", "organizer": "student_group", "start": 20 * 60, "end": 22 * 60, "attendees": 20, "will_show": True, "title": "Late lab session"},
    {"room": "rm_hub_006", "organizer": "student_group", "start": 21 * 60, "end": 22 * 60 + 30, "attendees": 12, "will_show": True, "title": "Board game night"},
    {"room": "rm_hsb_118", "organizer": "admin", "start": 21 * 60, "end": 22 * 60 + 30, "attendees": 15, "will_show": True, "title": "Facilities walkthrough"},
    {"room": "rm_allen_120", "organizer": "student_group", "start": 21 * 60, "end": 22 * 60, "attendees": 6, "will_show": True, "title": "Study group"},
    {"room": "rm_suzz_214", "organizer": "club", "start": 21 * 60 + 30, "end": 22 * 60 + 30, "attendees": 14, "will_show": True, "title": "Committee subcommittee"},
    {"room": "rm_hub_210", "organizer": "admin", "start": 22 * 60, "end": 23 * 60, "attendees": 9, "will_show": True, "title": "Late admin sync"},
    {"room": "rm_more_122", "organizer": "admin", "start": 22 * 60, "end": 23 * 60 + 30, "attendees": 12, "will_show": True, "title": "Building closure check"},
    {"room": "rm_odeg_118", "organizer": "student_group", "start": 22 * 60, "end": 23 * 60, "attendees": 5, "will_show": True, "title": "Study group"},
    {"room": "rm_suzz_305", "organizer": "admin", "start": 22 * 60, "end": 23 * 60 + 30, "attendees": 10, "will_show": True, "title": "Security briefing"},
    {"room": "rm_allen_402", "organizer": "student_group", "start": 22 * 60, "end": 23 * 60 + 30, "attendees": 11, "will_show": True, "title": "Final review session"},
]


#: Historical no-show counts per (organizer_type, weekday, hour).
#: Weekday 0 = Monday. These are the "model": a smoothed historical rate.
#: The signature is (organizer_type, weekday, hour) -> (bookings, noshows).
NOSHOW_HISTORY: list[tuple[str, int, int, int, int]] = [
    # Faculty: reliable, weekday business hours.
    ("faculty", 0, 9, 40, 6), ("faculty", 0, 10, 45, 8), ("faculty", 0, 11, 38, 5),
    ("faculty", 0, 13, 42, 7), ("faculty", 0, 14, 44, 6), ("faculty", 0, 16, 36, 5),
    ("faculty", 0, 17, 30, 6),
    ("faculty", 1, 9, 44, 6), ("faculty", 1, 10, 47, 7), ("faculty", 1, 11, 39, 5),
    ("faculty", 1, 13, 41, 6), ("faculty", 1, 14, 45, 7), ("faculty", 1, 16, 35, 5),
    ("faculty", 1, 17, 32, 7),
    ("faculty", 2, 9, 43, 7), ("faculty", 2, 10, 46, 6), ("faculty", 2, 11, 40, 6),
    ("faculty", 2, 13, 44, 8), ("faculty", 2, 14, 43, 6), ("faculty", 2, 16, 37, 6),
    ("faculty", 2, 17, 29, 6),
    ("faculty", 3, 9, 45, 6), ("faculty", 3, 10, 48, 7), ("faculty", 3, 11, 41, 6),
    ("faculty", 3, 13, 43, 6), ("faculty", 3, 14, 46, 8), ("faculty", 3, 16, 38, 6),
    ("faculty", 3, 17, 31, 7),
    ("faculty", 4, 9, 40, 9), ("faculty", 4, 10, 43, 10), ("faculty", 4, 11, 36, 8),
    ("faculty", 4, 13, 39, 9), ("faculty", 4, 14, 41, 11), ("faculty", 4, 16, 33, 9),
    ("faculty", 4, 17, 26, 8),
    # Student clubs: much worse - the classic Ghost Space offender.
    ("club", 0, 12, 18, 7), ("club", 0, 15, 22, 10), ("club", 0, 17, 20, 9),
    ("club", 0, 19, 16, 9), ("club", 0, 21, 12, 8),
    ("club", 1, 12, 19, 8), ("club", 1, 15, 24, 12), ("club", 1, 17, 21, 10),
    ("club", 1, 19, 18, 11), ("club", 1, 21, 13, 9),
    ("club", 2, 12, 17, 7), ("club", 2, 15, 21, 11), ("club", 2, 17, 19, 9),
    ("club", 2, 19, 15, 9), ("club", 2, 21, 11, 8),
    ("club", 3, 12, 20, 9), ("club", 3, 15, 23, 12), ("club", 3, 17, 22, 11),
    ("club", 3, 19, 17, 10), ("club", 3, 21, 14, 10),
    ("club", 4, 12, 16, 8), ("club", 4, 15, 19, 10), ("club", 4, 17, 18, 10),
    ("club", 4, 19, 14, 9), ("club", 4, 21, 10, 7),
    # Student groups: the worst offenders at off-hours.
    ("student_group", 0, 11, 14, 6), ("student_group", 0, 12, 16, 7),
    ("student_group", 0, 16, 15, 7), ("student_group", 0, 18, 14, 8),
    ("student_group", 0, 20, 12, 8), ("student_group", 0, 22, 9, 7),
    ("student_group", 1, 11, 15, 6), ("student_group", 1, 12, 17, 8),
    ("student_group", 1, 16, 16, 8), ("student_group", 1, 18, 15, 9),
    ("student_group", 1, 20, 13, 9), ("student_group", 1, 22, 10, 8),
    ("student_group", 2, 11, 14, 6), ("student_group", 2, 12, 16, 7),
    ("student_group", 2, 16, 15, 8), ("student_group", 2, 18, 14, 8),
    ("student_group", 2, 20, 12, 8), ("student_group", 2, 22, 9, 7),
    ("student_group", 3, 11, 16, 7), ("student_group", 3, 12, 18, 9),
    ("student_group", 3, 16, 17, 9), ("student_group", 3, 18, 16, 10),
    ("student_group", 3, 20, 14, 10), ("student_group", 3, 22, 11, 9),
    ("student_group", 4, 11, 13, 6), ("student_group", 12, 18, 12, 7),
    ("student_group", 4, 20, 10, 7), ("student_group", 4, 22, 8, 6),
    # Admin: middling.
    ("admin", 0, 10, 20, 5), ("admin", 0, 14, 18, 5), ("admin", 0, 17, 22, 8),
    ("admin", 0, 19, 16, 6), ("admin", 0, 21, 12, 5), ("admin", 0, 22, 10, 4),
    ("admin", 1, 10, 21, 5), ("admin", 1, 14, 19, 5), ("admin", 1, 17, 24, 9),
    ("admin", 1, 19, 17, 7), ("admin", 1, 21, 13, 6), ("admin", 1, 22, 11, 4),
    ("admin", 2, 10, 19, 4), ("admin", 2, 14, 20, 6), ("admin", 2, 17, 23, 8),
    ("admin", 2, 19, 18, 7), ("admin", 2, 21, 12, 5), ("admin", 2, 22, 9, 4),
    ("admin", 3, 10, 22, 6), ("admin", 3, 14, 18, 5), ("admin", 3, 17, 21, 8),
    ("admin", 3, 19, 16, 6), ("admin", 3, 21, 14, 6), ("admin", 3, 22, 10, 5),
    ("admin", 4, 10, 18, 5), ("admin", 4, 14, 17, 6), ("admin", 4, 17, 20, 9),
    ("admin", 4, 19, 15, 7), ("admin", 4, 21, 11, 5), ("admin", 4, 22, 9, 5),
]